display_name: Papyrus

icon: assets/logo.png

keywords:
  - Papyrus
  - paper
  - backup

generic_name: Papyrus


categories:
  - Utility
  - Development

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
# 
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []